package problem02;

/*
 Even Fibonacci numbers
 Problem 2
 Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:
      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
 */

public class FibonacciSum {
   public static void main(String[] args) {
      System.out.println(sum(4000000));
   }

   private static int sum(int max) {
      int first = 1;
      int second = 1;
      int sum = 0;
      while (second < max) {
         int temp = first;
         first = second;
         second = first + temp;
         if (second % 2 == 0) {
            sum += second;
         }
      }
      return sum;
   }
}
